// Generated by gencpp from file crazyflie_driver/UploadNN.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_UPLOADNN_H
#define CRAZYFLIE_DRIVER_MESSAGE_UPLOADNN_H

#include <ros/service_traits.h>


#include <crazyflie_driver/UploadNNRequest.h>
#include <crazyflie_driver/UploadNNResponse.h>


namespace crazyflie_driver
{

struct UploadNN
{

typedef UploadNNRequest Request;
typedef UploadNNResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UploadNN
} // namespace crazyflie_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_driver::UploadNN > {
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::crazyflie_driver::UploadNN&) { return value(); }
};

template<>
struct DataType< ::crazyflie_driver::UploadNN > {
  static const char* value()
  {
    return "crazyflie_driver/UploadNN";
  }

  static const char* value(const ::crazyflie_driver::UploadNN&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_driver::UploadNNRequest> should match 
// service_traits::MD5Sum< ::crazyflie_driver::UploadNN > 
template<>
struct MD5Sum< ::crazyflie_driver::UploadNNRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::UploadNN >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadNNRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::UploadNNRequest> should match 
// service_traits::DataType< ::crazyflie_driver::UploadNN > 
template<>
struct DataType< ::crazyflie_driver::UploadNNRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::UploadNN >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadNNRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_driver::UploadNNResponse> should match 
// service_traits::MD5Sum< ::crazyflie_driver::UploadNN > 
template<>
struct MD5Sum< ::crazyflie_driver::UploadNNResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_driver::UploadNN >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadNNResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_driver::UploadNNResponse> should match 
// service_traits::DataType< ::crazyflie_driver::UploadNN > 
template<>
struct DataType< ::crazyflie_driver::UploadNNResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_driver::UploadNN >::value();
  }
  static const char* value(const ::crazyflie_driver::UploadNNResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_UPLOADNN_H
