sudo: required
language: python
git:
  depth: 150
python:
  - "2.7"
services:
  - docker
before_install:
  - docker pull bitcraze/builder
script:
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build
